stages:
- name: Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./ci/Dockerfile-prod
      buildContext: .
      tag: expressways:${CICD_EXECUTION_SEQUENCE}
- name: Publish Image Nginx
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-nginx
      buildContext: .
      tag: expressways-nginx:${CICD_EXECUTION_SEQUENCE}
    env:
      AUTH0_NAMESPACE: https://wsp-lattice.io/
      PLUGIN_STORAGE_PATH: /var/lib/docker/2
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./ci/k8s/deployment.yml
  - applyYamlConfig:
      path: ./ci/k8s/ingress.yml
  - applyYamlConfig:
      path: ./ci/k8s/service.yml
# Ensure that these stages only run on the five branches.
branch:
  include: [ test, stag, prod ]

notification:
  recipients:
  - recipient: "#expressways_feeds"
    notifier: "c-jlrn6:n-5kvbs"
  condition:
  - Success
  - Changed
  - Failed
