version: "3.6"

services:
  flower:
    build: .
    command: bash -c /data/docker-flower-entrypoint.sh
    env_file:
      - '.env'
    ports:
      - 5555:5555
    restart: unless-stopped
    depends_on:
      - application
