version: '3.6'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    working_dir: /data
    command: 'gunicorn config.wsgi:application'
    env_file:
        - '.env'
    depends_on:
      - queue
    volumes:
      - static-files:/static
      - media-files:/media
    restart: unless-stopped
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    volumes:
      - static-files:/static:ro
      - media-files:/media:ro
    restart: unless-stopped
    depends_on:
      - application
  queue:
    image: redis:5
    expose:
      - 6379
    restart: unless-stopped
  worker:
    build: .
    command: bash -c /data/docker-worker-entrypoint.sh
    env_file:
      - '.env'
    restart: unless-stopped
    depends_on:
      - queue
      - application
volumes:
  static-files:
  media-files:
