version: '3.6'

services:
  application:
    ports:
      - 7000:8000
    volumes:
      - type: bind
        source: .
        target: /data
    environment:
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:8000 --reload --workers=3"
  proxy:
    ports:
      - 7080:80
  database:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: express
      POSTGRES_USER: express
      POSTGRES_DB: express
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /data/docker-flower-entrypoint.sh
    ports:
      - 5555:5555
  selenium-hub:
    image: selenium/hub
    environment:
      GRID_TIMEOUT: 60
      GRID_BROWSER_TIMEOUT: 60
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome-debug
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      SE_OPTS: -timeout 60 -browserTimeout 60
    ports:
      - 5900:5900
    depends_on:
      - selenium-hub
volumes:
  db-data:
