# Generated by Django 2.1.3 on 2018-12-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_occurrence_suboccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_closures', models.CharField(choices=[('II', 'II'), ('IX', 'IX'), ('XI', 'XI'), ('XX', 'XX')], default='II', max_length=2)),
                ('duration', models.PositiveIntegerField(choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60')], default=15)),
                ('flow', models.CharField(choices=[('H', 'High'), ('MH', 'Medium High'), ('ML', 'Medium Low'), ('L', 'Low')], default='H', max_length=2)),
                ('frequency', models.PositiveIntegerField()),
                ('sub_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubOccurrence')),
            ],
        ),
    ]
