# Generated by Django 2.1.3 on 2018-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_occurrenceconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='duration',
            field=models.PositiveIntegerField(choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60'), (120, '120'), (300, '300')], default=15),
        ),
    ]
