# Generated by Django 2.1.3 on 2019-03-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181214_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrenceconfiguration',
            name='occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Occurrence'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='sub_occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SubOccurrence'),
        ),
    ]
