# Generated by Django 2.1.3 on 2019-03-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='sub_occurrence',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.SubOccurrence'),
        ),
    ]
