# Generated by Django 2.1.3 on 2019-05-02 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_occurrence_configuration_speed_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_change', models.IntegerField(validators=[django.core.validators.MinValueValidator(-100)])),
                ('duration_change', models.IntegerField(validators=[django.core.validators.MinValueValidator(-100)])),
                ('justification', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='sub_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubOccurrence'),
        ),
        migrations.AddField(
            model_name='effectintervention',
            name='configuration_effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OccurrenceConfiguration', verbose_name='Effect on configuration'),
        ),
        migrations.AddField(
            model_name='effectintervention',
            name='design_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DesignComponent', verbose_name='Design component'),
        ),
        migrations.AddField(
            model_name='occurrenceconfiguration',
            name='effect',
            field=models.ManyToManyField(through='core.EffectIntervention', to='core.DesignComponent', verbose_name='Possible intervention'),
        ),
    ]
