# Generated by Django 2.1.3 on 2019-05-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_occurrence_configuration_speed_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_change', models.IntegerField()),
                ('duration_change', models.IntegerField()),
                ('justification', models.TextField()),
                ('design_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DesignComponent')),
            ],
        ),
        migrations.AddField(
            model_name='occurrenceconfiguration',
            name='effects',
            field=models.ManyToManyField(to='core.EffectIntervention', verbose_name='Possible intervention'),
        ),
    ]
