# Generated by Django 2.1.3 on 2019-05-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_design_component_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='sub_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubOccurrence'),
        ),
    ]
