# Generated by Django 2.1.3 on 2019-06-06 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_road_on_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcomponent',
            name='description',
            field=models.TextField(help_text='Provide a description of the design component, including any relevant references or supporting information'),
        ),
        migrations.AlterField(
            model_name='designcomponent',
            name='name',
            field=models.CharField(help_text='Provide a short, descriptive name', max_length=200),
        ),
        migrations.AlterField(
            model_name='effectintervention',
            name='design_component',
            field=models.ForeignKey(help_text='Select design component to create an impact score\u200b', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DesignComponent', verbose_name='Design component'),
        ),
        migrations.AlterField(
            model_name='effectintervention',
            name='duration_change',
            field=models.IntegerField(help_text='% change in duration', validators=[django.core.validators.MinValueValidator(-100)]),
        ),
        migrations.AlterField(
            model_name='effectintervention',
            name='frequency_change',
            field=models.IntegerField(help_text='% change in frequency', validators=[django.core.validators.MinValueValidator(-100)]),
        ),
        migrations.AlterField(
            model_name='effectintervention',
            name='justification',
            field=models.TextField(help_text='Provide a detailed explanation and references for the sources of the impact sources. Must be based on real data, published research or an assumption agreed with relevant subject matter experts'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='name',
            field=models.CharField(help_text='Provide a short, descriptive name', max_length=200),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='duration',
            field=models.PositiveIntegerField(choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60'), (120, '120'), (300, '300')], default=15, help_text='Select how long the incident occurs for. i.e. 2.5 = 0 to 5 minutes; 10 = 5 to 15 minutes; 25 = 15 to 30 minutes; 45 = 30 to 60 minutes; 90 = 60 to 120 minutes. Not required for "slow moving vehicle" or "all lanes open" incident.'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='flow',
            field=models.PositiveIntegerField(choices=[(1750, 'High'), (1250, 'Medium High'), (750, 'Medium Low'), (300, 'Low')], default=300, help_text='Select traffic flow condition: High = >1000 Medium = >400 <1000 Low = <400 (vph)\u200b', verbose_name='flow rate'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='frequency',
            field=models.PositiveIntegerField(help_text='Define the frequency of the occurrence (per mile per year)\u200b'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='lane_closures',
            field=models.CharField(choices=[('II', 'II'), ('IX', 'IX'), ('XI', 'XI'), ('XX', 'XX')], default='II', help_text='Select lane impact parameters i.e. II = all lanes open, XI = one lane closed (lane one or two), XX = both lanes closed, S = slow moving vehicle or WCH in lane\u200b', max_length=2, verbose_name='impact'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='road',
            field=models.ForeignKey(help_text='Select road/project name\u200b', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Road'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='speed_limit',
            field=models.PositiveIntegerField(choices=[(70, '70'), (60, '60'), (50, '50'), (40, '40')], default=70, help_text='Select prevailing traffic speed (mph) for given occurrence (set default to 70mph)\u200b\u200b'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='sub_occurrence',
            field=models.ForeignKey(help_text='Select sub-occurrence to edit, re-name the sub-occurrence or create a new entry\u200b', on_delete=django.db.models.deletion.CASCADE, to='core.SubOccurrence'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(help_text='Provide a short, descriptive name', max_length=200),
        ),
        migrations.AlterField(
            model_name='suboccurrence',
            name='name',
            field=models.CharField(help_text='Provide a short, descriptive name', max_length=200),
        ),
        migrations.AlterField(
            model_name='suboccurrence',
            name='occurrence',
            field=models.ForeignKey(help_text='Select ‘parent’ occurrence for the new sub-occurrence e.g. spillage (sub-occurrence) > Debris in road (parent occurrence). Add new occurrence if required.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_occurrences', to='core.Occurrence'),
        ),
    ]
