# Generated by Django 2.1.3 on 2019-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_help_text_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provide a short, descriptive name', max_length=200)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='duration',
            field=models.FloatField(choices=[(2.5, '2.5'), (10, '10'), (25, '25'), (45, '45'), (90, '90')], default=2.5, help_text='Select how long the incident occurs for. i.e. 2.5 = 0 to 5 minutes; 10 = 5 to 15 minutes; 25 = 15 to 30 minutes; 45 = 30 to 60 minutes; 90 = 60 to 120 minutes. Not required for "slow moving vehicle" or "all lanes open" incident.'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='flow',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', help_text='Select traffic flow condition: High = >1000 Medium = >400 <1000 Low = <400 (vph)\u200b', max_length=20, verbose_name='flow rate'),
        ),
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='lane_closures',
            field=models.CharField(choices=[('II', 'II'), ('XI', 'XI'), ('XX', 'XX'), ('S', 'S')], default='II', help_text='Select lane impact parameters i.e. II = all lanes open, XI = one lane closed (lane one or two), XX = both lanes closed, S = slow moving vehicle or WCH in lane\u200b', max_length=2, verbose_name='impact'),
        ),
    ]
