# Generated by Django 2.2.13 on 2020-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_static_values_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalobjective',
            name='identifier',
            field=models.CharField(default='', help_text='Operational objective identifier\u200b', max_length=10),
        ),
    ]
