# Generated by Django 2.2.13 on 2020-06-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_incidents_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrenceconfiguration',
            name='references',
            field=models.TextField(default='', help_text='Provide references to data sources or a detailed explanation of any assumptions used e.g. calculations to determine frequencies or durations.'),
        ),
    ]
