# Generated by Django 2.2.13 on 2020-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_references_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrenceconfiguration',
            name='duration',
            field=models.FloatField(choices=[(0, '0'), (2.5, '2.5'), (10.0, '10'), (25.0, '25'), (45.0, '45'), (90.0, '90')], default=2.5, help_text='Select how long the incident occurs for. i.e. 2.5 = 0 to 5 minutes; 10 = 5 to 15 minutes; 25 = 15 to 30 minutes; 45 = 30 to 60 minutes; 90 = 60 to 120 minutes. Not required for "slow moving vehicle" or "all lanes open" incident.'),
        ),
    ]
