# Generated by Django 2.1.3 on 2018-12-12 14:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField()),
                ('objective_1', models.PositiveIntegerField()),
                ('objective_2', models.PositiveIntegerField()),
            ],
        ),
    ]
