# Generated by Django 2.1.3 on 2018-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_auto_20181214_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='objective_1',
            field=models.FloatField(max_length=5),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='objective_2',
            field=models.FloatField(max_length=5),
        ),
    ]
