# Generated by Django 2.1.3 on 2018-12-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0003_auto_20181214_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='objective_1',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='objective_2',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
