# Generated by Django 2.1.3 on 2019-05-13 16:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0004_auto_20181214_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='config_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
