# Generated by Django 2.1.3 on 2019-05-28 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0005_calculation_with_config_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='component_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
