# Generated by Django 2.2.13 on 2020-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0007_calculationresult_freq_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='objective_1',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='objective_2',
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='objective_incident',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Objective for incidents cleared', max_digits=7),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='objective_journey',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Objective for acceptable journeys', max_digits=7),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='objective_pti',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Objective for planning time index', max_digits=7),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='objective_speed',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Objective for average speed', max_digits=7),
        ),
    ]
