---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressways-${CICD_GIT_BRANCH}
  labels:
    app: expressways-${CICD_GIT_BRANCH}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressways-${CICD_GIT_BRANCH}
  template:
    metadata:
      labels:
        app: expressways-${CICD_GIT_BRANCH}
    spec:    
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: expressways-application
          image: ${CICD_REGISTRY}/expressways:${CICD_EXECUTION_SEQUENCE}
          command: ['/data/docker-entrypoint.sh']
          workingDir: /data
          envFrom:
          - secretRef:
              name: application-${CICD_GIT_BRANCH}
        - name: expressways-worker
          image: ${CICD_REGISTRY}/expressways:${CICD_EXECUTION_SEQUENCE}
          command: ['/data/docker-worker-entrypoint.sh']
          workingDir: /data
          envFrom:
          - secretRef:
              name: worker-${CICD_GIT_BRANCH}
        - name: expressways-flower
          image: ${CICD_REGISTRY}/expressways:${CICD_EXECUTION_SEQUENCE}
          command: ['/data/docker-flower-entrypoint.sh']
          workingDir: /data
          envFrom:
          - secretRef:
              name: worker-${CICD_GIT_BRANCH}
        - name: queue
          image: redis:5
        - name: expressways-proxy
          image: ${CICD_REGISTRY}/expressways-nginx:${CICD_EXECUTION_SEQUENCE}
          ports
            - containerPort: 80
          volumeMounts:
            - name: static
              mountPath: /static
            - name: media
              mountPath: /media
      initContainers:
        - name: nginx-configuration
          image: ${CICD_REGISTRY}/expressways:${CICD_EXECUTION_SEQUENCE}
          command: ['/bin/sh', '-c', 'python3 /data/manage.py collectstatic && cp -rfv /static/* /expressways/static/']
          volumeMounts:
            - name: static
              mountPath: /expressways/static
            - name: media
              mountPath: /expressways/media
          envFrom:
          - secretRef:
              name: application-${CICD_GIT_BRANCH}
      volumes:
        - name: static
          emptyDir: {}
        - name: media 
          emptyDir: {}
