FROM quay.io/wspdigitalukteam/base-image:bionic
LABEL maintainer="Joel Merrick <joel.merrick@wsp.com>"
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get -y dist-upgrade && apt-get install --no-install-recommends -y build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /data
COPY requirements.txt /data
COPY requirements /data/requirements

RUN pip3 install -r /data/requirements.txt
COPY expressways /data/expressways
COPY config /data/config
COPY manage.py /data/manage.py
COPY docker-entrypoint.sh /data/docker-entrypoint.sh
COPY docker-worker-entrypoint.sh /data/docker-worker-entrypoint.sh
COPY docker-flower-entrypoint.sh /data/docker-flower-entrypoint.sh

RUN adduser --system --disabled-login wspreadonly && chown -R wspreadonly /data /static
USER wspreadonly
